# Generated by Django 2.0.5 on 2018-07-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VmRunning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=1024)),
                ('cpu', models.IntegerField(default=1)),
                ('memory', models.IntegerField(default=524288)),
                ('host_passthrough', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('state', models.IntegerField(choices=[(0, 'pending'), (1, 'stopped'), (2, 'running'), (3, 'destroyed'), (4, 'discard'), (5, 'deleted')], default=0)),
                ('persistent', models.BooleanField(default=True)),
                ('node', models.CharField(max_length=1024)),
                ('vnc_token', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VmTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('enable', models.BooleanField(default=True)),
                ('image_path', models.CharField(max_length=1024)),
                ('cpu', models.IntegerField(default=1)),
                ('memory', models.IntegerField(default=524288)),
                ('host_passthrough', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vmrunning',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='closestack.VmTemplate'),
        ),
    ]
