# Generated by Django 2.0.5 on 2018-07-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closestack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmrunning',
            name='vm_name',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
