# Generated by Django 2.0.5 on 2018-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closestack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmtemplate',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
