# Generated by Django 2.0.5 on 2018-07-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closestack', '0004_vmrunning_persistent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmrunning',
            name='vm_name',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
